{
 "title": "TLS 2.0 A-2",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "factory",
    "label": "Factory",
    "query": "select concat(f.fact_no, '#', f.fact_no, ' - ', f.fact_name)\n\tfrom cfg_user a\n\tinner join (select distinct group_id, user_pccuid from (\n\t\tselect group_id, user_pccuid from cfg_group_member \n\t\tunion all\n\t\tselect group_id, user_pccuid from cfg_group_mgr cgm \n\t\t) as group_user) b\n\t\ton a.user_pccuid = b.user_pccuid\n\tinner join cfg_group c\n\t\ton b.group_id = c.group_id \n\tinner join cfg_auth_board d \n\t\ton b.group_id = d.group_id and c.group_id = d.group_id\n\tinner join cfg_auth_dp_fact e \n\t\ton d.auth_board_id = e.auth_board_id \n\tinner join cfg_fact f\n\t\ton e.fact_id = f.fact_id  \n\tinner join cfg_board_dp_fact g\n\t\ton d.board_id = g.board_id and f.fact_id = g.fact_id and e.fact_id = g.fact_id  \n\tinner join cfg_board h \n\t\ton g.board_id = h.board_id \n\twhere a.user_pccuid = '${__user.login}'\n\tand a.enabled = 'Y'\n\tand f.enabled = 'Y'\n\tand f.fact_no <> '2151'\n\tand h.enabled = 'Y'\n\tand h.board_level = 1\n\tand h.board_gf_id = '${__dashboard.uid}'\n\tgroup by f.fact_no, f.fact_name \n\torder by f.fact_no, f.fact_name \n;"
   },
   {
    "name": "sec_no",
    "label": "Line Section",
    "query": " select concat(a.mainlineno,'#',a.sublineno) linesec\n from qmgt_rdb.cfg_mes_gf_aopgroupctrl a\n inner join qmgt_rdb.cfg_gf_fact b\n \ton a.fact_no_merge = b.fact_no_merge \n where a.fact_no_merge = '$factory'\n and a.stepname = 'ASB'\n and a.\"enable\" = 'Y'\n and b.\"enable\" = 'Y'\n group by a.mainlineno, a.sublineno \n order by a.mainlineno asc\n;\n"
   },
   {
    "name": "process",
    "label": "Process",
    "query": "select concat(c.process_no, ' | ', c.process_desc, '#', c.process_id) as process\n\tfrom qmgt_rdb.tls_gf_inspection a\n\tinner join qmgt_rdb.tls_gf_inspection_defect b on a.tls_inspection_id = b.tls_inspection_id \n\tinner join qmgt_rdb.cfg_gf_process c on a.process_id = c.process_id \n  \tinner join qmgt_rdb.cfg_gf_fact_process d on a.fact_no_merge = d.fact_no_merge and c.process_id = d.process_id\n\tinner join qmgt_rdb.cfg_mes_gf_aopgroupctrl e on a.opgroup_id = e.opgroup_id and a.fact_no_merge = e.fact_no_merge and d.line_type = e.line_type \nwhere a.fact_no_merge = '$factory'\n\tand a.inspection_date between '${__from:date:YYYYMMDD}' and '${__to:date:YYYYMMDD}'\n\tand a.defect_qty <> 0 \n\tand c.\"enable\" = 'Y'\n\tand d.\"enable\" = 'Y'\n\tand e.\"enable\" = 'Y'\n\tand e.mainlineno = '$sec_no'\ngroup by c.process_no, c.process_desc, c.process_id \norder by c.process_no asc;"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<script>\n  let userRole = window.grafanaBootData.user.orgRole;\n\n  if (userRole != 'Admin') {\n    let breadcrumbs = document.querySelector('[aria-label=\"Breadcrumbs\"]');\n    let toggle = document.querySelector('[aria-label=\"Toggle menu\"]');\n    let markFavoriteIcon = document.querySelector('[aria-label=\"Mark as favorite\"]');\n    let shareIcon = document.querySelector('[aria-label=\"Share dashboard or panel\"]');\n    //hard coce..\n    let headerBlocks = document.querySelectorAll('[data-testid=\"wrapper\"]');\n\n    //hide dom if exists\n    if (breadcrumbs){\n      breadcrumbs.style.display = 'none';\n    }\n    if (toggle) {\n      toggle.style.display = 'none';\n    }\n    if (markFavoriteIcon) {\n      markFavoriteIcon.style.display = 'none';\n    }\n    if (shareIcon){\n      shareIcon.style.display = 'none';\n    }\n\n    if (headerBlocks.length > 0) {\n      //keep dom's space\n      headerBlocks[1].style.visibility = 'hidden';\n    }\n  }\n</script>"
   }
  },
  {
   "title": "RFT Pass Trend ${sec_no} | ${__from:date:YYYY-MM-DD} ~ ${__to:date:YYYY-MM-DD}",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select\r\n  sum(\r\n    case\r\n      when insp <> 0 then pass / insp * 100\r\n      else 0\r\n    end\r\n  ) as RFT_Data,\r\n  RFT_Date\r\nfrom\r\n  (\r\n    select\r\n      sum(a.inspection_qty) as insp,\r\n      sum(a.pass_qty) as pass,\r\n      substr(cast(a.inspection_date as varchar), 5, 4) as RFT_Date\r\n    from\r\n      qmgt_rdb.tls_gf_inspection a\r\n      inner join qmgt_rdb.cfg_mes_gf_aopgroupctrl b on a.fact_no_merge = b.fact_no_merge\r\n      and a.opgroup_id = b.opgroup_id\r\n    where\r\n      a.fact_no_merge = '$factory'\r\n      and substr(cast(a.inspection_date as varchar), 0, 9) between '${__from:date:YYYYMMDD}'\r\n      and '${__to:date:YYYYMMDD}'\r\n      and b.mainlineno = '$sec_no'\r\n      and b.\"enable\" = 'Y'\r\n    group by\r\n      substr(cast(a.inspection_date as varchar), 5, 4)\r\n  ) as sub\r\ngroup by\r\n  rft_date\r\norder by\r\n  rft_date asc;"
    }
   ]
  },
  {
   "title": "Defect $process",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "options": {
    "content": "<table align=\"center\" style=\"board:0px;font-size:24px\">\n{{#each data}}\n  <tr style=\"board:0px\">\n    <td style=\"board:0px\">Check Quantity : </td>\n    <td>{{c1}}</td>\n  </tr>\n  <tr style=\"board:0px\">\n    <td style=\"board:0px; color:{{c4}}\">Defect Quantity</td>\n    <td>{{c2}}</td>\n  </tr>\n  <tr style=\"board:0px\">\n    <td style=\"board:0px; color:{{c4}}\">Defect Rate</td>\n    <td>{{c3}}</td>\n  </tr style=\"board:0px\">\n{{/each}}\n</table>"
   },
   "targets": [
    {
     "rawSql": "select\r\n  rft.insp as c1,\r\n  rft.def as c2,\r\n  concat(round(rft.def / rft.insp * 100, 2), '%') as c3\r\nfrom\r\n  (\r\n    select\r\n      sum(a.inspection_qty) as insp,\r\n      sum(a.defect_qty) as def\r\n    from\r\n      qmgt_rdb.tls_gf_inspection a\r\n      inner join qmgt_rdb.cfg_mes_gf_aopgroupctrl b on a.fact_no_merge = b.fact_no_merge\r\n      and a.opgroup_id = b.opgroup_id\r\n    where\r\n      a.fact_no_merge = '$factory'\r\n      and a.inspection_date between '${__from:date:YYYYMMDD}'\r\n      and '${__to:date:YYYYMMDD}'\r\n      and a.process_id = '$process'\r\n      and a.defect_qty <> 0\r\n      and b.\"enable\" = 'Y'\r\n      and b.mainlineno = '$sec_no'\r\n  ) rft;"
    }
   ]
  },
  {
   "title": "Top 5 Critical Process | ${__from:date:YYYY-MM-DD} ~ ${__to:date:YYYY-MM-DD}",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select\r\n  concat(c.process_no, ' | ', c.process_desc) as cpname,\r\n  sum(a.defect_qty) as cpvalue\r\nfrom\r\n  qmgt_rdb.tls_gf_inspection a\r\n  inner join qmgt_rdb.tls_gf_inspection_defect b on a.tls_inspection_id = b.tls_inspection_id\r\n  inner join qmgt_rdb.cfg_gf_process c on a.process_id = c.process_id\r\n  inner join qmgt_rdb.cfg_mes_gf_aopgroupctrl d on a.opgroup_id = d.opgroup_id\r\n  inner join qmgt_rdb.cfg_gf_fact_process e on c.process_id = e.process_id\r\n  and d.line_type = e.line_type\r\nwhere\r\n  a.fact_no_merge = '$factory'\r\n  and a.inspection_date between '${__from:date:YYYYMMDD}'\r\n  and '${__to:date:YYYYMMDD}'\r\n  and c.\"enable\" = 'Y'\r\n  and d.\"enable\" = 'Y'\r\n  and e.\"enable\" = 'Y'\r\ngroup by\r\n  c.process_desc,\r\n  c.process_id\r\norder by\r\n  cpvalue desc, cpname desc\r\nlimit\r\n  5;"
    }
   ]
  },
  {
   "title": "Top 5 Defect ${sec_no} | ${__from:date:YYYY-MM-DD} ~ ${__to:date:YYYY-MM-DD}",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "select\r\n  c.defect_desc as tdname,\r\n  SUM(b.defect_num) as tdvalue\r\nfrom\r\n  qmgt_rdb.tls_gf_inspection a\r\n  inner join qmgt_rdb.tls_gf_inspection_defect b on a.tls_inspection_id = b.tls_inspection_id\r\n  inner join qmgt_rdb.cfg_gf_defect c on b.defect_id = c.defect_id\r\n  inner join qmgt_rdb.cfg_mes_gf_aopgroupctrl d on a.fact_no_merge = d.fact_no_merge\r\n  and a.opgroup_id = d.opgroup_id\r\nWHERE\r\n  a.fact_no_merge = '$factory'\r\n  and a.inspection_date between '${__from:date:YYYYMMDD}'\r\n  and '${__to:date:YYYYMMDD}'\r\n  and c.\"enable\" = 'Y'\r\n  and d.\"enable\" = 'Y'\r\n  and d.mainlineno = '$sec_no'\r\ngroup by\r\n  c.defect_desc\r\norder by\r\n  tdvalue desc, tdname desc\r\nlimit\r\n  5;"
    },
    {
     "rawSql": "select\r\n  mainlineno as workcenter,\r\n  line_type as linetype\r\nfrom\r\n  qmgt_rdb.cfg_mes_gf_aopgroupctrl\r\nwhere\r\n  fact_no_merge = '$factory'\r\n  and opgroup_id = '$sec_no'\r\n  and \"enable\" = 'Y'\r\ngroup by\r\n  mainlineno,\r\n  line_type;"
    }
   ]
  }
 ]
}